name: "Release Build"

on:
  schedule:
    # Weekly unstable trigger on Monday at 05:00 GMT
    - cron: '0 5 * * 1'
  workflow_dispatch:
    # Manual trigger from bot
    inputs:
      version:
        required: true
        type: string
        description: 'The server and web stable release tag ("vX.Y.Z") or "master"'

env:
  SDK_VERSION: "9.0.x"

permissions:
  contents: read

jobs:
  Nuget:
    runs-on: ubuntu-24.04
    steps:
      - name: "Set dated version for unstable builds"
        id: version
        run: |-
          if grep --silent --extended-regexp '^v[0-9]+' <<< "${{ inputs.version || 'master' }}"; then
            echo "JELLYFIN_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
            echo "JELLYFIN_RELEASE_TYPE=stable" >> $GITHUB_ENV
          else
            echo "JELLYFIN_VERSION=$(date +'%Y%m%d%H')" >> $GITHUB_ENV
            echo "JELLYFIN_RELEASE_TYPE=unstable" >> $GITHUB_ENV
            echo "DEBUG_FLAG=--debug" >>$GITHUB_ENV
          fi

      - name: "Install dependencies"
        run: |-
          sudo apt-get update
          sudo apt-get install --yes python3-git python3-yaml

      - name: "Setup .NET"
        uses: actions/setup-dotnet@67a3573c9a986a3f9c594539f4ab511d57bb3ce9 # v4.3.1
        with:
          dotnet-version: ${{ env.SDK_VERSION }}

      - name: "Checkout repository"
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: "Prepare repository"
        run: |-
          ./checkout.py ${{ inputs.version || 'master' }}

      - name: "Run builder for Nuget"
        env:
          NUGET_STABLE_KEY: ${{ secrets.NUGET_STABLE_KEY }}
          NUGET_UNSTABLE_KEY: ${{ secrets.NUGET_UNSTABLE_KEY }}
        run: |-
          which dotnet
          dotnet --version
          sudo --preserve-env ./build.py ${{ env.JELLYFIN_VERSION }} nuget
